<a href="https://colab.research.google.com/github/aninarafath6/mechine_learning/blob/main/numpy_is(indexing_and_slicing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Indexing and Slicing***

We can access data from numpy array by it's index . it is similar to list.

In [2]:
import numpy as np

In [35]:
def arrDetials(arr):
    print(arr)
    print()
    print("Size : ",arr.size)
    print("Shape : ",arr.shape)
    print("Dimension : {} Dimmensional  array".format(arr.ndim))
    print("Type : ",arr.dtype)

In [19]:
my_list = [10,20,30,40,50]
arr = np.array(my_list,dtype="int64")
arrDetials(arr)



Array :  [10 20 30 40 50]
Size :  5
Shape :  (5,)
Dimension :  1
Type :  int64


# Access Element through index

In [12]:
arr[1]
arr[2]

30

In [14]:
arr[-2] #negative indexing it will give values from last

40

In [28]:
arr = np.array([[1,2,3],[4,5,6]])
arrDetials(arr)


# we can access data by these two methods
print(arr[1,1])
print(arr[1][1])

# for getting first row 
print(arr[0])
# for getting second row
print(arr[1])

[[1 2 3]
 [4 5 6]]

Size :  6
Shape :  (2, 3)
Dimension :  2
Type :  int64
5
5
[1 2 3]
[4 5 6]


In [41]:
#3D Array
arr = np.random.randint(1,9,(2,3,4))
arrDetials(arr)


[[[1 4 5 8]
  [3 4 5 4]
  [2 2 6 8]]

 [[3 3 1 8]
  [2 4 3 7]
  [4 3 1 8]]]

Size :  24
Shape :  (2, 3, 4)
Dimension : 3 Dimmensional  array
Type :  int64


In [44]:
print(arr[1,2,3])

8


# ***Slicing***
which is similar to python list.

In [49]:
arr = np.arange(10)
arrDetials(arr)

[0 1 2 3 4 5 6 7 8 9]

Size :  10
Shape :  (10,)
Dimension : 1 Dimmensional  array
Type :  int64


In [51]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[5:]

array([5, 6, 7, 8, 9])

In [56]:
arr[:5]

array([0, 1, 2, 3, 4])

In [67]:
arr = np.random.randint(1,9,(4,4))
arrDetials(arr)


[[3 3 5 6]
 [2 3 4 7]
 [4 3 8 3]
 [2 5 6 5]]

Size :  16
Shape :  (4, 4)
Dimension : 2 Dimmensional  array
Type :  int64


In [71]:
arr[:3,-1]

array([6, 7, 3])

In [73]:
#start:end:step_size
arr[2,::2]

array([4, 8])

## ***Indexing Using Arrays***

In [74]:
arr

array([[3, 3, 5, 6],
       [2, 3, 4, 7],
       [4, 3, 8, 3],
       [2, 5, 6, 5]])

In [76]:
arr[np.array([1,3])]

array([[2, 3, 4, 7],
       [2, 5, 6, 5]])

## ***Slicing with boolean***

In [79]:
arr[arr<5]

array([3, 3, 2, 3, 4, 4, 3, 3, 2])