<a href="https://colab.research.google.com/github/aninarafath6/mechine_learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Start With NUMPY ( Numerical Python)**

In [27]:
import numpy as np

#inbuilt list in python
sample_list = ["Apple","Orange","grapes"]
sample_list

['Apple', 'Orange', 'grapes']

# Properties of Numpy Array


1.   Size of array (arr.size) 
2.   Dimension of array (arr.ndim)
3.   Shape of array (arr.shape)



In [28]:
arr = np.array(sample_list,dtype="str")

print("array: ",arr)
print("size: ",arr.size)
print("Dimension: ",arr.ndim)
print("Shape: ",arr.shape)
print("Type: ",arr.dtype)
print("Item Size: ",arr.itemsize)




array:  ['Apple' 'Orange' 'grapes']
size:  3
Dimension:  1
Shape:  (3,)
Type:  <U6
Item Size:  24


In [29]:
arr2 = np.array([[1,2],[3,4]],dtype="int64")

print(arr2)
print("size: ",arr2.size)
print("Dimension: ",arr2.ndim)
print("Shape: ",arr2.shape)
print("Type: ",arr2.dtype)
print("Item Size : ",arr2.itemsize)


[[1 2]
 [3 4]]
size:  4
Dimension:  2
Shape:  (2, 2)
Type:  int64
Item Size :  8


# **Complex Data Type's Array**
complex numbers is basic data type in python 
it is in the form **a+ib**.

In [31]:
complex_list = [1,2,3,4,5]
arr3 = np.array(complex_list,dtype="complex")
print("Array: ",arr3)
print("size: ",arr3.size)
print("Dimension: ",arr.ndim)
print("Shape: ",arr3.shape)
print("Type: ",arr3.dtype)
print("Item Size : ",arr3.itemsize)
print("Imaginary Parts: ",arr3.imag)
print("Real Parts: ",arr3.real)


Array:  [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
size:  5
Dimension:  1
Shape:  (5,)
Type:  complex128
Item Size :  16
Imaginary Parts:  [0. 0. 0. 0. 0.]
Real Parts:  [1. 2. 3. 4. 5.]


# ***Placeholder Arrays***

we can easly initialize array with zero by using zeros method. and we need to provide the shape of the array on there.


In [41]:
arr6=np.zeros((2),dtype="int64",)
arr7=np.zeros((3,3),dtype="int64",)

print("Array 6 :",arr6)
print()
print("Array 7: ",arr7)



Array 6 : [0 0]

Array 7:  [[0 0 0]
 [0 0 0]
 [0 0 0]]
