<a href="https://colab.research.google.com/github/aninarafath6/mechine_learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Start With NUMPY ( Numerical Python)**

In [ ]:
import numpy as np

#inbuilt list in python
sample_list = ["Apple","Orange","grapes"]
sample_list

['Apple', 'Orange', 'grapes']

# Properties of Numpy Array


1.   Size of array (arr.size) 
2.   Dimension of array (arr.ndim)
3.   Shape of array (arr.shape)



In [ ]:
arr = np.array(sample_list,dtype="str")

print("array: ",arr)
print("size: ",arr.size)
print("Dimension: ",arr.ndim)
print("Shape: ",arr.shape)
print("Type: ",arr.dtype)
print("Item Size: ",arr.itemsize)




array:  ['Apple' 'Orange' 'grapes']
size:  3
Dimension:  1
Shape:  (3,)
Type:  <U6
Item Size:  24


In [ ]:
arr2 = np.array([[1,2],[3,4]],dtype="int64")

print(arr2)
print("size: ",arr2.size)
print("Dimension: ",arr2.ndim)
print("Shape: ",arr2.shape)
print("Type: ",arr2.dtype)
print("Item Size : ",arr2.itemsize)


[[1 2]
 [3 4]]
size:  4
Dimension:  2
Shape:  (2, 2)
Type:  int64
Item Size :  8


# **Complex Data Type's Array**
complex numbers is basic data type in python 
it is in the form **a+ib**.

In [ ]:
complex_list = [1,2,3,4,5]
arr3 = np.array(complex_list,dtype="complex")
print("Array: ",arr3)
print("size: ",arr3.size)
print("Dimension: ",arr.ndim)
print("Shape: ",arr3.shape)
print("Type: ",arr3.dtype)
print("Item Size : ",arr3.itemsize)
print("Imaginary Parts: ",arr3.imag)
print("Real Parts: ",arr3.real)


Array:  [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
size:  5
Dimension:  1
Shape:  (5,)
Type:  complex128
Item Size :  16
Imaginary Parts:  [0. 0. 0. 0. 0.]
Real Parts:  [1. 2. 3. 4. 5.]


# ***Placeholder Arrays***

we can easly initialize array with zero by using zeros method. and we need to provide the shape of the array on there.

At the sametime we can use numpy.ones() for creating arrays

In [ ]:
arr6=np.zeros((2),dtype="int64",)
arr7=np.zeros((3,3),dtype="int64",)
arr8=np.ones((2,2),dtype="int64",)


print("Array 6 :",arr6)
print()
print("Array 7: ",arr7)
print()
print("Array 8: ",arr8)




Array 6 : [0 0]

Array 7:  [[0 0 0]
 [0 0 0]
 [0 0 0]]

Array 8:  [[1 1]
 [1 1]]


Random array

In [ ]:
arry9=np.empty((3,3),)
print("Array 9: ",arry9)
np.random.randint(1,9,(10,10))

Array 9:  [[2.92427574e-316 1.77863633e-322 0.00000000e+000]
 [0.00000000e+000 8.48798316e-313 2.25285501e+184]
 [7.61485367e+169 7.11820985e-091 7.25487042e+169]]


array([[7, 2, 2, 2, 5, 3, 5, 8, 1, 1],
       [5, 5, 1, 6, 2, 6, 6, 2, 6, 5],
       [5, 3, 8, 3, 2, 5, 2, 3, 2, 5],
       [4, 7, 3, 1, 3, 3, 3, 1, 8, 8],
       [2, 3, 1, 4, 4, 6, 2, 4, 5, 1],
       [8, 4, 7, 1, 3, 4, 6, 8, 8, 8],
       [6, 2, 8, 8, 2, 5, 7, 7, 1, 1],
       [7, 7, 8, 2, 1, 6, 6, 3, 4, 4],
       [2, 3, 2, 5, 2, 4, 1, 1, 1, 4],
       [6, 5, 7, 5, 7, 2, 1, 5, 8, 7]])

Fill with value 


In [ ]:
np.full((10,10),"A")

#dimension of array will take of the dimension of array9
np.full_like(arry9,20)

array([[20., 20., 20.],
       [20., 20., 20.],
       [20., 20., 20.]])

In [ ]:
#Digonal Elements are ones
np.identity(4,dtype="int64")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1.1,11,2)

array([1.1, 3.1, 5.1, 7.1, 9.1])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Creating array by using external file

In [24]:
marks = np.loadtxt("sample 2.txt",skiprows=1,dtype="int64")
print("Shape: ", marks.shape)
print()
marks


Shape:  (3, 3)



array([[ 1, 28, 30],
       [ 2, 40, 50],
       [ 3, 60, 70]])

# For seperation
Taking the transforse of matrix for seperation

In [28]:
data1,data2,data3 = np.loadtxt("sample 2.txt",skiprows=1,unpack=True,dtype="int64")
print("1st: ",data1)
print("2nd: ",data2)
print("3rd: ",data3)

1st:  [1 2 3]
2nd:  [28 40 60]
3rd:  [30 50 70]


In [29]:
# for storing data on npy 
np.save("savedData",data1)
np.load("savedData.npy")

array([1, 2, 3])

# Create array from a function

In [38]:
#from a function 
np.fromfunction(lambda i,j:i*j,dtype="int64",shape=(4,8))

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 0,  3,  6,  9, 12, 15, 18, 21]])