In [52]:
# Import Essential packages
import numpy as np
from py_md import *


<img src="./data/axis.jpeg">

In [53]:
# scalar operation 
arr = np.random.randint(11,20,(4,2))
get_details(arr)

array:
 [[17 12]
 [14 12]
 [14 17]
 [18 14]]
size:  8
Dimension:  2
Shape:  (4, 2)
Type:  int64
Item Size:  8


In [54]:
# scalar operations on ndarray
arr+ 2

array([[19, 14],
       [16, 14],
       [16, 19],
       [20, 16]])

In [55]:
# scalar substraction
arr -1

array([[16, 11],
       [13, 11],
       [13, 16],
       [17, 13]])

In [56]:
# scalar multiplication
print(arr *2 )
print(arr **2 ) # power of 2

[[34 24]
 [28 24]
 [28 34]
 [36 28]]
[[289 144]
 [196 144]
 [196 289]
 [324 196]]


In [57]:
arr_2 = np.random.randint(11,20,(2,4))
get_details(arr_2)

array:
 [[11 14 11 11]
 [11 17 13 14]]
size:  8
Dimension:  2
Shape:  (2, 4)
Type:  int64
Item Size:  8


In [58]:
# arr + arr_2
# must be same dimension

In [59]:
# arr * arr_2
# must be same dimension


In [60]:
# must be same dimension
# arr / arr_2

In [61]:
#dont product of matrix
arr.dot(arr_2)

array([[319, 442, 343, 355],
       [286, 400, 310, 322],
       [341, 485, 375, 392],
       [352, 490, 380, 394]])

In [62]:
a = np.array([1,2,0,1,1,0,1])
b = np.array([1,2,3,1,1,0,1,])

a== b

array([ True,  True, False,  True,  True,  True,  True])

In [63]:
np.logical_or(a,b)

array([ True,  True,  True,  True,  True, False,  True])

In [64]:
np.logical_and(a,b)

array([ True,  True, False,  True,  True, False,  True])

In [76]:
# Statistical Operations
print("Sin :"+str(np.sin(b)))
print("Cos :"+str(np.cos(b)))
print("Mean :"+str(np.mean(b)))
print("Median :"+str(np.median(b)))
print("Standard Deviation :"+str(np.std(b)))







Sin :[0.84147098 0.90929743 0.14112001 0.84147098 0.84147098 0.
 0.84147098]
Cos :[ 0.54030231 -0.41614684 -0.9899925   0.54030231  0.54030231  1.
  0.54030231]
Mean :1.2857142857142858
Median :1.0
Standard Deviation :0.880630571852711
