In [1]:
# essential Packages
import numpy as np
from py_md import *


In [2]:
#Load data from file
marks = np.loadtxt("data/data.txt",skiprows=1,dtype=int)
get_details(marks)

array:
 [[10 20 30]
 [20 40 50]
 [30 60 70]
 [40 80 80]]
size:  12
Dimension:  2
Shape:  (4, 3)
Type:  int64
Item Size:  8


In [3]:
# unpacking
# taking the transpose
marks = np.loadtxt("data/data.txt",skiprows=1,dtype=int,unpack=True)
mark1,mark2 ,mark3= marks;
print("Mark1: "+str(mark1))
print("Mark2: "+str(mark2))
print("Mark3: "+str(mark3))





get_details(marks)


Mark1: [10 20 30 40]
Mark2: [20 40 60 80]
Mark3: [30 50 70 80]
array:
 [[10 20 30 40]
 [20 40 60 80]
 [30 50 70 80]]
size:  12
Dimension:  2
Shape:  (3, 4)
Type:  int64
Item Size:  8


In [4]:
np.save("sample",np.array([1,2,3]))

In [5]:
arr = np.fromfunction(lambda i,j:i+j,(4,4),dtype=int)
get_details(arr)

array:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
size:  16
Dimension:  2
Shape:  (4, 4)
Type:  int64
Item Size:  8
