## **Numpy in Action**

In [38]:
import numpy as np
from py_md import * 
from matplotlib.image import imread


 <img width='210' src="./data/cat.avif"/>  <img width='210' src="./data/dog.jpg"/> <img width='210' height="210" src="./data/dog.webp"/> 

In [44]:
# Turn an image into numpy array
cat = imread("./data/axis.jpeg")
get_details(mouse)


array:
 [[[ 89  87  92]
  [ 89  87  92]
  [ 90  88  93]
  ...
  [ 99 118  72]
  [ 99 118  72]
  [ 99 118  72]]

 [[ 89  87  92]
  [ 89  87  92]
  [ 90  88  93]
  ...
  [ 99 118  72]
  [ 99 118  72]
  [ 99 118  72]]

 [[ 89  86  93]
  [ 89  86  93]
  [ 90  87  94]
  ...
  [ 99 118  72]
  [ 99 118  72]
  [ 99 118  72]]

 ...

 [[222 199 149]
  [215 191 143]
  [198 176 129]
  ...
  [206 184 187]
  [206 184 187]
  [206 184 187]]

 [[223 201 152]
  [230 208 159]
  [219 197 150]
  ...
  [208 186 189]
  [208 186 189]
  [208 186 189]]

 [[222 201 154]
  [223 202 155]
  [219 198 153]
  ...
  [208 186 189]
  [208 186 189]
  [209 187 190]]]
size:  16652553
Dimension:  3
Shape:  (2113, 2627, 3)
Type:  uint8
Item Size:  1
