In [1]:
# essential Packages
import numpy as np
from py_md import *


In [2]:
#Load data from file
marks = np.loadtxt("data/data.txt",skiprows=1,dtype=int)
get_details(marks)

array:
 [[10 20]
 [20 40]
 [30 60]
 [40 80]]
size:  8
Dimension:  2
Shape:  (4, 2)
Type:  int64
Item Size:  8


In [5]:
# unpacking
# taking the transpose
marks = np.loadtxt("data/data.txt",skiprows=1,dtype=int,unpack=True)
mark1,mark2 = marks;
print("Mark1: "+str(mark1))
print("Mark2: "+str(mark2))




get_details(marks)


Mark1: [10 20 30 40]
Mark2: [20 40 60 80]
array:
 [[10 20 30 40]
 [20 40 60 80]]
size:  8
Dimension:  2
Shape:  (2, 4)
Type:  int64
Item Size:  8


In [6]:
np.save("sample",np.array([1,2,3]))

In [13]:
arr = np.fromfunction(lambda i,j:i+j,(2,8),dtype=int)
get_details(arr)

array:
 [[0 1]
 [1 2]]
size:  4
Dimension:  2
Shape:  (2, 2)
Type:  int64
Item Size:  8
