In [1]:
# essential packages
import numpy as np
from py_md import get_details,cdts


In [2]:
# string of array
str_list = ["apple","orange","grape","mango"]
arr = np.array(str_list)
get_details(arr)

array:
 ['apple' 'orange' 'grape' 'mango']
size:  4
Dimension:  1
Shape:  (4,)
Type:  <U6
Item Size:  24


In [3]:
#complex data type 
complex_list = [1,2,3,4]
arr = np.array(complex_list,dtype="complex")
get_details(arr,cdts)

array:
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
size:  4
Dimension:  1
Shape:  (4,)
Type:  complex128
Item Size:  16
Imaginary: [0. 0. 0. 0.]
Real: [1. 2. 3. 4.]


In [4]:
#Boolean Numpy array
arr = np.array([1,2,3,0,3,0,2,10,0,0],dtype="bool")
get_details(arr)


array:
 [ True  True  True False  True False  True  True False False]
size:  10
Dimension:  1
Shape:  (10,)
Type:  bool
Item Size:  1


In [5]:
#Placeholder 
arr = np.zeros(9,dtype=int)
get_details(arr)

array:
 [0 0 0 0 0 0 0 0 0]
size:  9
Dimension:  1
Shape:  (9,)
Type:  int64
Item Size:  8


In [10]:
arr = np.zeros((3,3),dtype=int)
get_details(arr)

array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
size:  9
Dimension:  2
Shape:  (3, 3)
Type:  int64
Item Size:  8


In [14]:
arr = np.ones((2,3),dtype=int)
get_details(arr)

array:
 [[1 1 1]
 [1 1 1]]
size:  6
Dimension:  2
Shape:  (2, 3)
Type:  int64
Item Size:  8


In [15]:
# random
arr = np.empty((3,4),dtype=int)
get_details(arr)

array:
 [[481036337249 463856468080          101 489626271855]
 [472446402657 433791696999 489626271847 481036337249]
 [         101 416611827821 442381631598          111]]
size:  12
Dimension:  2
Shape:  (3, 4)
Type:  int64
Item Size:  8


In [16]:
# fill with some value her its "9"
arr = np.full((2,3),9)
get_details(arr)

array:
 [[9 9 9]
 [9 9 9]]
size:  6
Dimension:  2
Shape:  (2, 3)
Type:  int64
Item Size:  8
