In [1]:
# essential packages
import numpy as np
from py_md import get_details,cdts


In [2]:
# string of array
str_list = ["apple","orange","grape","mango"]
arr = np.array(str_list)
get_details(arr)

array:
 ['apple' 'orange' 'grape' 'mango']
size:  4
Dimension:  1
Shape:  (4,)
Type:  <U6
Item Size:  24


In [3]:
#complex data type 
complex_list = [1,2,3,4]
arr = np.array(complex_list,dtype="complex")
get_details(arr,cdts)

array:
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
size:  4
Dimension:  1
Shape:  (4,)
Type:  complex128
Item Size:  16
Imaginary: [0. 0. 0. 0.]
Real: [1. 2. 3. 4.]


In [4]:
#Boolean Numpy array
arr = np.array([1,2,3,0,3,0,2,10,0,0],dtype="bool")
get_details(arr)


array:
 [ True  True  True False  True False  True  True False False]
size:  10
Dimension:  1
Shape:  (10,)
Type:  bool
Item Size:  1


In [5]:
#Placeholder 
arr = np.zeros(9,dtype=int)
get_details(arr)

array:
 [0 0 0 0 0 0 0 0 0]
size:  9
Dimension:  1
Shape:  (9,)
Type:  int64
Item Size:  8


In [10]:
arr = np.zeros((3,3),dtype=int)
get_details(arr)

array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
size:  9
Dimension:  2
Shape:  (3, 3)
Type:  int64
Item Size:  8


In [14]:
arr = np.ones((2,3),dtype=int)
get_details(arr)

array:
 [[1 1 1]
 [1 1 1]]
size:  6
Dimension:  2
Shape:  (2, 3)
Type:  int64
Item Size:  8


In [15]:
# array with random values
arr = np.empty((3,4),dtype=int)
get_details(arr)

array:
 [[481036337249 463856468080          101 489626271855]
 [472446402657 433791696999 489626271847 481036337249]
 [         101 416611827821 442381631598          111]]
size:  12
Dimension:  2
Shape:  (3, 4)
Type:  int64
Item Size:  8


In [18]:
arr = np.random.rand(2,3)
get_details(arr)

array:
 [[0.85016074 0.22052067 0.06233656]
 [0.35637099 0.67972197 0.48877999]]
size:  6
Dimension:  2
Shape:  (2, 3)
Type:  float64
Item Size:  8


In [22]:
arr = np.random.randint(1,9,(3,3))
get_details(arr)

array:
 [[8 1 8]
 [5 6 1]
 [5 7 2]]
size:  9
Dimension:  2
Shape:  (3, 3)
Type:  int64
Item Size:  8


In [16]:
# fill with some value her its "9"
arr = np.full((2,3),9)
get_details(arr)

array:
 [[9 9 9]
 [9 9 9]]
size:  6
Dimension:  2
Shape:  (2, 3)
Type:  int64
Item Size:  8


In [29]:
# identity matrix
arr =np.identity(5,dtype=int)
get_details(arr)

array:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
size:  25
Dimension:  2
Shape:  (5, 5)
Type:  int64
Item Size:  8


In [30]:
arr = np.arange(6)
get_details(arr)

array:
 [0 1 2 3 4 5]
size:  6
Dimension:  1
Shape:  (6,)
Type:  int64
Item Size:  8


In [31]:
arr = np.arange(10,20)
get_details(arr)

array:
 [10 11 12 13 14 15 16 17 18 19]
size:  10
Dimension:  1
Shape:  (10,)
Type:  int64
Item Size:  8


In [32]:
# a range function with step size 
arr = np.arange(1,11,2)
# -> start -> end -> step size
get_details(arr)

array:
 [1 3 5 7 9]
size:  5
Dimension:  1
Shape:  (5,)
Type:  int64
Item Size:  8


In [33]:
# step size in floating values 
arr = np.arange(1,11,.2)
get_details(arr)

array:
 [ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8]
size:  50
Dimension:  1
Shape:  (50,)
Type:  float64
Item Size:  8
