In [1]:
import numpy as np
from py_md import *


In [2]:
arr = np.random.randint(1,20,(2,5))
get_details(arr)

array:
 [[13  1  8 12 16]
 [10 10  8  9  1]]
size:  10
Dimension:  2
Shape:  (2, 5)
Type:  int64
Item Size:  8


In [4]:
arr = arr.reshape((5,2))
get_details(arr)

array:
 [[13  1]
 [ 8 12]
 [16 10]
 [10  8]
 [ 9  1]]
size:  10
Dimension:  2
Shape:  (5, 2)
Type:  int64
Item Size:  8


In [11]:
arr = arr.reshape((1,2,5))
get_details(arr)

array:
 [[[13  1  8 12 16]
  [10 10  8  9  1]]]
size:  10
Dimension:  3
Shape:  (1, 2, 5)
Type:  int64
Item Size:  8


In [13]:
# repeat an array
arr = np.array([1,2,3,4])
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [18]:
arr = np.array([[1,2,3],[1,2,3]])
get_details(arr)

np.repeat(arr,2,axis=1)

array:
 [[1 2 3]
 [1 2 3]]
size:  6
Dimension:  2
Shape:  (2, 3)
Type:  int64
Item Size:  8


array([[1, 1, 2, 2, 3, 3],
       [1, 1, 2, 2, 3, 3]])

In [25]:
# vertical stacking
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1,v2,[7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])