**Essential Packages**

In [1]:
import numpy as np
from py_md import  *

print(np.__version__)

1.24.2


In [2]:
#crate an array 
list = [1,2,3,4,5]

numpy_array = np.array(list,dtype='int32')
numpy_array[0] = 22.2
numpy_array

array([22,  2,  3,  4,  5], dtype=int32)

In [3]:
print(type(list))
print(type(numpy_array))
print("\n================================\n")
get_details(numpy_array)

<class 'list'>
<class 'numpy.ndarray'>


array:  [22  2  3  4  5]
size:  5
Dimension:  1
Shape:  (5,)
Type:  int32
Item Size:  4


In [2]:
# 2 dimensional array (Matrix)


list = [[1,2,3],[2,3,4]]
#complex data type 
np_arr = np.array(list,dtype="complex")
get_details(np_arr,cdts)




array:
 [[1.+0.j 2.+0.j 3.+0.j]
 [2.+0.j 3.+0.j 4.+0.j]]
size:  6
Dimension:  2
Shape:  (2, 3)
Type:  complex128
Item Size:  16
Imaginary: [[0. 0. 0.]
 [0. 0. 0.]]
Real: [[1. 2. 3.]
 [2. 3. 4.]]


array([[1.+0.j, 2.+0.j, 3.+0.j],
       [2.+0.j, 3.+0.j, 4.+0.j]])

In [5]:
# 3 Dimensional Numpy arrays
three_dims_list = [[[1,2],[3,4]],[[1,2],[3,4]]]
np_arr = np.array(three_dims_list,dtype="int64")

get_details(np_arr)

array:  [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
size:  8
Dimension:  3
Shape:  (2, 2, 2)
Type:  int64
Item Size:  8
