In [1]:
# essential Packages
import numpy as np
from py_md import *


In [2]:
#Load data from file
marks = np.loadtxt("data/data.txt",skiprows=1,dtype=int)
get_details(marks)

array:
 [[10 20]
 [20 40]
 [30 60]
 [40 80]]
size:  8
Dimension:  2
Shape:  (4, 2)
Type:  int64
Item Size:  8


In [1]:
# unpacking
# taking the transpose
marks = np.loadtxt("data/data.txt",skiprows=1,dtype=int,unpack=True)
mark1,mark2 ,mark3= marks;
print("Mark1: "+str(mark1))
print("Mark2: "+str(mark2))
print("Mark3: "+str(mark3))





get_details(marks)


NameError: name 'np' is not defined

In [6]:
np.save("sample",np.array([1,2,3]))

In [16]:
arr = np.fromfunction(lambda i,j:i+j,(4,4),dtype=int)
get_details(arr)

array:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
size:  16
Dimension:  2
Shape:  (4, 4)
Type:  int64
Item Size:  8
