**Indexing and Slicing**

In [2]:
import numpy as np
from py_md import *

In [9]:
# from random ndarray
# in 1D array

arr = np.random.randint(1,9,(1))
get_details(arr)

print("Item : "+str(arr[0]))

array:
 [3]
size:  1
Dimension:  1
Shape:  (1,)
Type:  int64
Item Size:  8
Item : 3


In [11]:
# in 2D array
arr = np.random.randint(1,9,(2,2))
get_details(arr)

print("Item : "+str(arr[0,1]))




array:
 [[4 6]
 [5 5]]
size:  4
Dimension:  2
Shape:  (2, 2)
Type:  int64
Item Size:  8
Item : 6


In [16]:
# in the case of 3D array
arr = np.random.randint(1,9,(3,3,3))
get_details(arr)

print("Item : "+str(arr[1,1,2]))



array:
 [[[6 4 2]
  [6 8 1]
  [7 6 5]]

 [[1 6 5]
  [5 5 4]
  [7 1 6]]

 [[7 1 2]
  [4 2 3]
  [2 6 6]]]
size:  27
Dimension:  3
Shape:  (3, 3, 3)
Type:  int64
Item Size:  8
Item : 4


In [17]:
#Slicing 
arr = np.array([1,2,3,4,5,6,7,8,9,10])
get_details(arr)

print(arr[1:5])

array:
 [ 1  2  3  4  5  6  7  8  9 10]
size:  10
Dimension:  1
Shape:  (10,)
Type:  int64
Item Size:  8
[2 3 4 5]


In [43]:
#Slicing in 2D array 
arr  = np.random.randint(1,9,(3,6))
get_details(arr)

print("======== Sliced in 2D array =================")
print(arr[-1:,::2])
# with step size

array:
 [[3 6 7 3 8 2]
 [2 2 8 7 7 3]
 [4 8 4 7 8 7]]
size:  18
Dimension:  2
Shape:  (3, 6)
Type:  int64
Item Size:  8
======== Sliced in 2D array =================
[[4 4 8]]


In [46]:
arr = np.arange(1,20)
get_details(arr)
 
condition = arr <= 10
arr[condition]

array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
size:  19
Dimension:  1
Shape:  (19,)
Type:  int64
Item Size:  8


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])